### ISSUE TITLE
:building_construction:: 피드 작성 페이지/수정 페이지/헤더 컴포넌트 프레임구축 

### ISSUE THREAD

**Issue by kuetiipp** [E24I/TOGEDOG#14]
## Description 💬
목업 작업을 위한 피드 작성 페이지와 수정 페이지, 헤더의 레이아웃을 구축합니다.

## To-Do ✅
- [x] 피드 작성 페이지 프레임 구축
- [x] 피드 수정 페이지 프레임 구축
- [x] 헤더 컴포넌트 생성
- [x] 피드 작성 페이지 라우터 추가

## Expected Deadline 🏁
23/1/10

## Reference 📚
[레이아웃](https://www.figma.com/file/fFf0dnz385yYfbuKqnnN2J/layout?type=design&node-id=0%3A1&mode=design&t=LUk6FhRAnzmxTIws-1)
