### ISSUE TITLE
📱 디자인 작업

### ISSUE THREAD

**Issue by JB0129** [E24I/TOGEDOG#255]
## Description 💬
- 전체적인 디자인 수정 작업 예정입니다.

## To-Do ✅
- [x] 전체 피드 페이지 CSS 작업
- [x] 피드 상세 모달 CSS 작업
- [x] 모달 창들에 대한 CSS 작업
- [x] Styled-component 통일화 작업
- [x] 다크모드 적용 작업
- [x] pet map 페이지 CSS 작업

## Expected Deadline 🏁
- 1/21

## Reference 📚
- `none`
