### ISSUE TITLE
✨ : 서버 application yml 파일 분리

### ISSUE THREAD

**Issue by hae02y** [E24I/TOGEDOG#27]
## Description 💬
서버 application yml 파일을 분리합니다.
**dev** : 개발 DB 환경
**prod** : 배포 DB 환경

dev파일을 로컬에서 원하는 입맛대로 세팅해서 사용하면 됩니다. (H2 사용, MySQL 사용등 선택)
**_전역으로 적용되는 설정은 application.yml에 세팅해주세요._**

## To-Do ✅
- [x] application.yml 생성
- [x] application-dev.yml 생성 (개인 로컬용)
- [x] application-prod.yml 생성(배포 용)
- [x] 테스트

## Expected Deadline 🏁
1Day
