### ISSUE TITLE
✨ : 공용 컴포넌트 재사용화 만들기

### ISSUE THREAD

**Issue by JB0129** [E24I/TOGEDOG#77]
## Description 💬
- 공용 컴포넌트 재사용화 만들기

## To-Do ✅
- [ ] 좋아요, 북마크 버튼 생성
- [ ] alert, confirm 등 모달창 생성
- [ ] setting 모달창 수정

## Expected Deadline 🏁
- ~11/23(목)

## Reference 📚
- `none`
